apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anythingllm

resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: anythingllm
  app.kubernetes.io/name: anythingllm
  app.kubernetes.io/part-of: llm-on-openshift
