apiVersion: v1
kind: ServiceAccount
metadata:
  name: anythingllm
  namespace: anythingllm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anythingllm-restricted-v2
  namespace: anythingllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-v2
subjects:
- kind: ServiceAccount
  name: anythingllm
  namespace: anythingllm
